### ISSUE TITLE
Undefined symbol: _ZNK11KGestureMap20defaultRockerGestureEPK7QAction

### ISSUE THREAD

**Issue by codingepaduli** [flathub/org.kde.kolourpaint#16]
When I run KolourPaint, i have the following error:

`flatpak run org.kde.kolourpaint`
`kolourpaint: symbol lookup error: /app/lib/libKF5KDELibs4Support.so.5: undefined symbol: _ZNK11KGestureMap20defaultRockerGestureEPK7QAction`

`flatpak --version`
`Flatpak 1.2.5`

I have all the flatpak dependencies installed, like xdg-desktop-portal-gtk and xdg-desktop-portal-kde.

Additional info:
`flatpak info org.kde.kolourpaint`
`          ID: org.kde.kolourpaint`
`         Ref: app/org.kde.kolourpaint/x86_64/stable`
`        Arch: x86_64`
`      Branch: stable`
`     Version: 19.12.0`
`     License: BSD-2-Clause and LGPL-2.0+ and GFDL-1.2`
`      Origin: flathub`
`  Collection: org.flathub.Stable`
`Installation: system`
`   Installed: 13,7 MB`
`     Runtime: org.kde.Platform/x86_64/5.13`
`         Sdk: org.kde.Sdk/x86_64/5.13`
`      Commit: 484f5b29ad3e256ced7499dcb1aa467b6b058a0ca2e5c5f1d3ccd9f02f450470`
`      Parent: abd574a218275bdd9c60f7130803c8c2c26cca28562e17ed1c78d61f0ca881f8`
`     Subject: Update to KDE Applications 19.12.0 (b8aa8119)`
`        Date: 2019-12-12 22:10:58 +0000`

Can you check it, please?

**Comment by tsdgeos** [comment]
Yes, the KDE Frameworks people did a big mistake, i'll try to get a fix out soon-ish bug can't promise it'll be today

**Comment by tsdgeos** [comment]
Fixed now, thanks a lot for reporting :)
