### ISSUE TITLE
Cannot save image to home folder

### ISSUE THREAD

**Issue by Sl0vi** [flathub/org.kde.kolourpaint#2]
OS: Linux Mint 18.3 MATE

When I click save in kolourpaint, the home folder in the save dialog doesn't actually point to my home folder.

The entire file system shown in the save dialog isn't my actual file system but looks more like a sandbox but I'm not sure where this sandbox is located.

**Comment by nedrichards** [comment]
This sounds like an issue with the portals since this app uses xdg-destop-portals (and the gtk or kde implementations) to share files into and out of the sandbox. What versions of those packages do you have?
