### ISSUE TITLE
Kolourpaint on Wayland won't allow one to copy and paste out of the program

### ISSUE THREAD

**Issue by suryaya** [flathub/org.kde.kolourpaint#20]
Hi,

Would just like to report a bug. I am using Gnome 3.34 on Ubuntu 19.10. I installed the flatpak to use but was unable to copy something from kolourpaint and into some other program (into my browser, or libre office etc).

This feature works just fine on the kolourpaint snap (I have not tried the deb). 

Additionally (not sure if this is related?) on wayland, Kolourpaint follows a theme totally different to what I'm using (some sort of dark theme with no close/minimize buttons at the top), while in Xorg it looks normal. Everything works fine in the snap.

**Comment by eszlari** [comment]
Does it work if you start kolourpaint with:
```
flatpak run --env=QT_QPA_PLATFORM=xcb org.kde.kolourpaint
```

**Comment by grulja** [comment]
It works for me on KDE Plasma running on Wayland. It's likely some incompatibility with Mutter. As for the theme, you need to install **org.kde.KStyle.Adwaita** (-dark) and **org.kde.PlatformTheme.QGnomePlatform**. Can you try debian package?

**Comment by suryaya** [comment]
Hi, thanks for the responses

@eszlari - Yes, if I run it like that, it works perfectly fine. Also, the adwaita theme titlebars show up.

**Comment by suryaya** [comment]
@grulja The deb package (which I got from apt-get) works fine, if I use QT_QPA_PLATFORM=wayland variable. However it takes 5-10 seconds to start every time, for some reason. But it follows system theme.

**Comment by eszlari** [comment]
@suryaya Could you please open a bug report on https://bugs.kde.org?
