### ISSUE TITLE
[help with issue] the kolourpaint is showing the old icons, it that an issue with the breeze theme or the kolourpaint?

### ISSUE THREAD

**Issue by Viliansh** [flathub/org.kde.kolourpaint#74]
![image](https://github.com/flathub/org.kde.kolourpaint/assets/72302817/e4e8495a-5df5-4628-a856-8df60ca7ba9f)
![image](https://github.com/flathub/org.kde.kolourpaint/assets/72302817/39c1db58-aeb5-4635-8f02-4e07726a2cb6)
the new icon was supposed to be the default, no?, i need to make a issue/pull request to the breeze icons or here?

**Comment by travier** [comment]
I've pushed the KF6 update. Can you check once that update is available if you still have this issue? Thanks

**Comment by Viliansh** [comment]
yep, it's fixed thanks!
