### ISSUE TITLE
Launcher does not find Kolourpaint on string "paint"

### ISSUE THREAD

**Issue by SRNissen** [flathub/org.kde.kolourpaint#80]
### Issue

On Pop!_OS, but presumably also other distros that use flatpaks:

### Repro

1. Install Kolourpaint
2. Open the launcher
3. Type "paint"

### Expected

Kolourpaint will be among the apps found

### Actual

Kolourpaint is not among the apps found, see also image:

![image](https://github.com/flathub/org.kde.kolourpaint/assets/4851097/0364a3b4-a6f3-40a6-bb23-41cd78584783)

### Additional:

> it looks like it may (?) be caused by KolourPaint lacking a "Keywords" entry in its .desktop file

https://github.com/pop-os/launcher/issues/167#issuecomment-1780388408

**Comment by Justinzobel** [comment]
If it is lacking keywords in the desktop file, please file the bug with KDE at https://bugs.kde.org

However, I have installed this Flatpak, and it shows for me when typing Paint in KDE's launcher. So I'd suggest perhaps filing this with Pop!OS as well as they should be searching for partial matches of the application name.
