### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by MayeulC** [flathub/org.kde.kolourpaint#9]
The current Flathub icon is low-res, which makes it look pixelated.

I think some better icons are available, as highlighted in https://phabricator.kde.org/D21521

Not sure if flathub/flatpak supports SVG icons, though?

**Comment by glaubersm** [comment]
Low resolution icon persists with Kolourpaint 19.12.

**Comment by eszlari** [comment]
> I think some better icons are available, as highlighted in https://phabricator.kde.org/D21521

These icons seems to be part of the breeze theme, they are not included in kolourpaint's tarball.

I opened a bug upstream:
https://bugs.kde.org/show_bug.cgi?id=418444
